


from enum import Enum

class ElevatorState(Enum):
    STOPPED = "STOPPED"
    MOVING = "MOVING"
    DOORS_OPENING = "DOORS_OPENING"
    DOORS_CLOSING = "DOORS_CLOSING"
    MAINTENANCE = "MAINTENANCE"
    PRE_MAINTENANCE = "PRE_MAINTENANCE"