import uuid
import sys
import os

# Add the project root to the sys.path so modules can be found
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from controller.payment_controller import PaymentController
from domain.payment_request import PaymentRequest
from domain.payment_gateways import PaymentGateWays
from domain.payment_methods import PaymentMethod
from domain.transaction_status import TransactionStatus
from domain.user import User
from repository.payment_repository import PaymentRepository
from repository.user_repository import UserRepository
from service.locking_service import LockService
from service.payment_service import PaymentService

def main():
    print("=== Initializing Payment Gateway System ===")
    
    # 1. Initialize Repositories
    payment_repo = PaymentRepository()
    user_repo = UserRepository()

    # 2. Initialize Services
    lock_service = LockService()

    payment_service = PaymentService(
        payment_repository=payment_repo,
        user_repository=user_repo,
        locking_service=lock_service
    )

    # 3. Initialize Controller
    payment_controller = PaymentController(payment_service=payment_service)

    import pdb;pdb.set_trace()
    # 4. Create and Save User
    print("\n--- Creating User ---")
    user = User(id=1, username="john_doe", email="john@example.com", name="John Doe")
    user_repo.save(user)
    print(f"User created: {user.name} (ID: {user.id})")

    # 5. Create a Payment Request
    request_id = str(uuid.uuid4())
    print(f"\n--- Creating Payment Request (Request ID: {request_id}) ---")
    
    payment_request = PaymentRequest(
        sender="user_123",
        receiver="merchant_456",
        amount=1500.0,
        currency="INR",
        gateway=PaymentGateWays.RAZORPAY,
        payment_method=PaymentMethod.UPI,
        user_id=user.id,
        request_id=request_id
    )

    # 6. Process Payment via Controller
    print("\n--- Processing Payment ---")
    try:
        response = payment_controller.process_payment(payment_request)
        print("Payment Response:")
        print(f"  Payment ID: {response.payment_id}")
        
        # Note: Response status might be an Enum depending on how strategy handles it.
        # We print it cleanly below.
        status_name = response.status.name if hasattr(response.status, 'name') else response.status
        print(f"  Status: {status_name}")
        print(f"  Transaction ID: {response.transaction_id}")
        print(f"  Message: {response.message}")
    except Exception as e:
        print(f"Error processing payment: {e}")
        return

    # 7. Simulate Webhook Callback from Gateway
    print("\n--- Simulating Webhook Callback from Payment Gateway ---")
    
    # We retrieve the transaction to get the gateway_transaction_id generated by the strategy
    transaction = payment_repo.find_by_id(response.transaction_id)
    
    if transaction and transaction.gateway_transaction_id:
        gateway_txn_id = transaction.gateway_transaction_id
        print(f"Received webhook for Gateway Transaction ID: {gateway_txn_id}")
        
        # Simulate a successful payment callback
        payment_controller.handle_payment_callback(
            provider_ref=gateway_txn_id, 
            status=TransactionStatus.SUCCESS
        )
        
        # Fetch the transaction again to verify that the status has been updated
        updated_txn = payment_repo.find_by_id(response.transaction_id)
        print(f"Transaction Status after callback: {updated_txn.status.name}")
    else:
        print("Transaction or Gateway Transaction ID not found in repository.")


if __name__ == "__main__":
    main()
